name: zebra_rfid_reader
description: Flutter plugin for reading rfid tags.
repository: https://github.com/suatkeskin/zebra_rfid_reader/tree/main/zebra_rfid_reader
issue_tracker: https://github.com/suatkeskin/zebra_rfid_reader/issues
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

flutter:
  plugin:
    platforms:
      android:
        default_package: zebra_rfid_reader_android

dependencies:
  flutter:
    sdk: flutter
  zebra_rfid_reader_android: ^1.0.0
  zebra_rfid_reader_platform_interface: ^1.0.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

topics:
  - zebra
  - rfid
  - mc3300x
