name: zebra_rfid_reader_android
description: Android implementation of the zebra_rfid_reader_android plugin
repository: https://github.com/suatkeskin/zebra_rfid_reader/tree/main/zebra_rfid_reader_android
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

flutter:
  plugin:
    implements: zebra_rfid_reader
    platforms:
      android:
        package: com.zebra.plugins.rfid
        pluginClass: ZebraRfidReaderPlugin
        dartPluginClass: ZebraRfidReaderAndroid

dependencies:
  flutter:
    sdk: flutter
  stream_transform: ^2.1.1
  zebra_rfid_reader_platform_interface: ^1.0.0

dev_dependencies:
  build_runner: ^2.7.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.5.0
  pigeon: ^26.0.2

topics:
  - zebra
  - rfid
  - mc3300x