name: zebra_rfid_reader_android
description: Android implementation of the zebra_rfid_reader_android plugin
repository: https://github.com/suatkeskin/zebra_rfid_reader/zebra_rfid_reader_android
version: 1.0.0

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=3.3.0'

flutter:
  plugin:
    implements: zebra_rfid_reader
    platforms:
      android:
        package: com.zebra.plugins.rfid
        pluginClass: ZebraRfidReaderPlugin
        dartPluginClass: ZebraRfidReaderAndroid

dependencies:
  flutter:
    sdk: flutter
  stream_transform: ^2.1.0
  #  zebra_rfid_reader_platform_interface: ^1.0.0
  zebra_rfid_reader_platform_interface:
    path: ../zebra_rfid_reader_platform_interface

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.4.4
  pigeon: ^20.0.2

topics:
  - zebra
  - rfid mc3300x