name: zebra_rfid_reader_platform_interface
description: Android implementation of the zebra_rfid_reader_platform_interface plugin.
repository: https://github.com/suatkeskin/zebra_rfid_reader/tree/main/zebra_rfid_reader_android
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.1
  plugin_platform_interface: ^2.1.8
  stream_transform: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.5.1

topics:
  - zebra
  - rfid
  - mc3300x