name: zebra_rfid_reader_android_example
description: "Demonstrates how to use the zebra_rfid_reader_android plugin."
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

  stream_transform: ^2.1.1
  zebra_rfid_reader_platform_interface: ^1.0.0
  zebra_rfid_reader_android:
    path: ../

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
